use_frameworks!

target 'SwiftyPluralizer_Example' do
  pod 'SwiftyPluralizer', :path => '../'

  target 'SwiftyPluralizer_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.9.3'
    pod 'Nimble', '~> 4.1.0'
  end
end
