use_frameworks!

target 'SwiftyPluralizer_Example' do
  pod 'SwiftyPluralizer', :path => '../'

  target 'SwiftyPluralizer_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
